apiVersion: v1
kind: Service
metadata:
  name: {{ include "rrelayer.fullname" . }}
  labels:
    {{- include "rrelayer.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rrelayer.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
